### ISSUE TITLE
Error During Ingest

### ISSUE THREAD

**Issue by parker20121** [Sotera/newman#104]
I tried running your application using the quick start instructions with two different gmail accounts. It responds with only with a dialog with the message "Error" on it. Not sure where to even start debugging what happened.

![error](https://cloud.githubusercontent.com/assets/351878/15303212/90de397a-1b84-11e6-9186-8bc160d51468.png)

**Comment by eickovic** [comment]
These instructions are outdated, this will be patched over the next few days.

**Comment by ghost** [comment]
new version of loaded Newman 2.0 does not loading properly ingest html to process pst file
![screenshot from 2016-05-27 16 20 46](https://cloud.githubusercontent.com/assets/16864128/15610727/0ddd2d8c-2427-11e6-9a9c-a6306e877403.png)

**Comment by smahoney58** [comment]
New Ingest instructions have been included in Help documentation. Ingest was moved from Quick Start to Features and includes steps to ingest using GUI.
