### ISSUE TITLE
Unable to start virtual box on Ubuntu image

### ISSUE THREAD

**Issue by ajspencer** [Sotera/newman#109]
I'm connected to an Ubuntu image and wanted to run the application on that. I used the quick start guide and received an error with the command  `vagrant up`
My error is depicted below:
![image](https://cloud.githubusercontent.com/assets/9373721/16095841/710b3f06-3314-11e6-8cec-d49f810c2492.png)

**Comment by smahoney58** [comment]
You should get the latest Newman which is v2.1.1. The version in your screenshot is (v1.1.2 is not supported). I'm in the process of updating the documentation to reflect the latest versions and setup.

**Comment by ajspencer** [comment]
@smahoney58 okay, cool. I got the virtual box from the quick start guide at https://sotera.github.io/newman/quick-start/.

**Comment by smahoney58** [comment]
Hello Andrew,

We need to update the quick start guide (see bottom of email to see what it will eventually look like minus the troubleshooting issues I ran into). The latest Newman is v2.1.1 and is located here https://www.dropbox.com/s/vwfjlncq488u35r/newman-vm-v2.1.1.box?dl=0.  This virtual box comes pre-loaded with the shiavo dataset. For test purposes, I ingested my sotera defense emails. I ran into a couple stumbling blocks.

```
    1 - The UI implies the file needs to be compressed but currently that is not supported. So, ingest pst files that are not compressed.
    2 – Need to place the pst file in the vagrant root directory. For me that was C:/users/smahoney/VirtualBoxVMs.
    3 – Currently there is no status on the progress of the ingest. It’s a feature that’s in work. However, there is a workaround. You can check  http://localhost:8787/ingester/status.  Also there are logs for the ingest in /srv/software/newman/work_dir/. The service should return the file id but you can check by timestamps also.
```

4       – The time it takes to ingest a file is dependent on the system environment and size of file of being ingested. On my system, it took about 10 minutes to ingest a 180MB pst.

You can create a pst file from Outlook 2010 by following these steps:

·        On the Home tab, in the New group, click New Items, point to More Items, and then click Outlook Data File.

·        In the Create or Open Outlook Data File dialog box, in the File name box, type the name as you want it to appear in the Outlook Navigation Pane, and then click OK.

Updated Quick Start Guide

Local installation
Pre-requisites
1. ```
   Install Vagrant<http://www.vagrantup.com/>.
   ```
   
   I downloaded the WINDOWS Universal (32 and 64-bit) version. This created the file vagrant_1.8.1.msi in my Downloads folder. Double-click on this file and accept the default location of C:\HashiCorp\Vagrant. Vagrant installation is complete.
2. ```
   Install Virtual Box<https://www.virtualbox.org/wiki/Downloads>
   ```
   
   I downloaded the latest Oracle VirtualBox 5.0.20 for Windows hosts x86/amd64. This created the file VirtualBox-5.0.20-106931-Win.exe in mydownloads folder. Double-click on this file and accept the default location C:\Program Files\Oracle\VirtualBox. VirtualBox is now installed.

Note: I initially had problems with version mismatch between Vagrant and Virtual Box. If you pull later vrsions of Vagrant or VirtualBox, just make sure they are compatible.
1.     SSH client installed.
   I updated my Path System variable to include location of Git. Select Start button , right-click on Computer, select Properties, select Advanced system settings link, select Environment Variables… button, scroll to System Variables Path and then select it, select the Edit… button, scroll to the end of the text field and add C:\Program Files (x86)\Git;C:\Program Files (x86)\Git\bin. GIT isn’t necessarily required but a SSH client is. Other options include installing Cygwin, MinGW or your personal favorite SSH client. I included steps to install Git at the bottom of this setup if that is your preference for SSH client.

Newman setup
1. ```
   Download the latest Newman Release. The latest file as of 4/18/2016 3:38PM is newman-vm-v2.1.1.box   (https://www.dropbox.com/s/vwfjlncq488u35r/newman-vm-v2.1.1.box?dl=0).
   ```
2. ```
   Copy from Download directory to a known location like C:\Users\jsmith\VirtualBoxVMs\
   ```
3. ```
   Open a CMD terminal. Select Windows Start icon, type cmd, select cmd.exe.
   ```
4. ```
   Change directory to virtualboxvms\
   ```

cd virtualboxvms

The prompt should now be something like C:\Users\jsmith\virtualboxvms>.
1.     Type in the following command:
   C:\Users\jsmith\virtualboxvms\vagrant init newman-vm-v2.1.1 newman-vm-v2.1.1.box
   A ‘Vagranfile’ has been placed in this directory. You are now ready to ‘vagrant up’ your first virtual environment! Please read the comments in the Vagrantfile as well as documentation on the ‘vagrant.com’ for more information on using Vagrant.

Note: if you have already executed a vagrant init, then you will get an error stating a Vagrantfile exists. Just delete or rename the Vagrantfile and the .vagrant folder and all its contents and re-run command.
1.     Type in the following command:

C:\Users\jsmith\virtualboxvms\vagrant up
Bringing machine ‘default’ up with ‘virtualbox’ provider …
Note: this step did not initially work. The system would basically hang with the message above displayed. It took over a day to figure out that the version of Vagrant and/or VirtualBox was the issue. Most likely it was just the version of Vagrant that caused the hang. I matched Elliot’s version of both (Vagrant 1.7.4/VirtualBox 4.3.24) to get around the problem. When the step is working a lot more text scrolls across the cmd terminal and it takes about 15 minutes before the cmd prompt comes back.
1.     Type in the following command:

C:\Users\jsmith\virtualboxvms\Newman\vagrant ssh

vagrant@vagrant-ubuntu-trusty-64:/$
Note: in the past, when I tried to execute this step, I ran into the error ‘ssh’ executable not found in any directories in the %PATH% variable. Is an SSH client installed? Try installing Cygwin, MinGW or Git, all of which contain an SSH client. Or use your favorite SSH client with the following authentication information shown below: ... To fix this error, I updated my Path System variable to include location of Git. Select Start button , right-click on Computer, select Properties, select Advanced system settings link, select Environment Variables… button, scroll to System Variables Path and then select it, select the Edit… button, scroll to the end of the text field and add C:\Program Files (x86)\Git;C:\Program Files (x86)\Git\bin. After updating Path system variable, you need to re-start your system.

Note: Fixing this issue implies that you already have Git installed. Git isn’t necessarily required but a SSH client is. I do not know the steps to install Cygwin, MinGW or personal favorite SSH clients. So, if you do not have Git installed or a SSH client. Follow the Git Installation instructions at the bottom of this paper.
1.     Type in the following command:

vagrant@vagrant-ubuntu-trusty-64:/$tangelo restart

Git Installation
-   Select this link http://git-scm.com/downloads and then Windows platform. As of 2/4/15, this downloads file Git-1.9.5-preview20141217.exe to your Downloads folder.
-   Double-click on executable, accept default location C:\Program Files (x86)\Git. Git is now installed.
-   Select this link http://sourceforge.net/projects/gitextensions/ to install Git Extensions.
-   Select the Download button. Creates a file called GitExtensions-2.48.03-SetupComplete.msi.
-   Double-click on Git Extension installer and follow  prompts.  Git Extensions now installed with a shortcut icon on the desktop.

Let me know if there is anything I can help you with.

-Scott Mahoney

**Comment by smahoney58** [comment]
Closing issue. I have successfully setup multiple Newman systems; the latest being v2.1.3. Will re-open if receive further feedback on problems setting up a Newman system.
