### ISSUE TITLE
ingest error  with giving back  â€ after adding new dataset

### ISSUE THREAD

**Issue by ghost** [Sotera/newman#112]
Extractor home set to /srv/software/pst-extraction-master/
email_address=newman-6643554f-5a82-11e6-a100-080027542fa4 parent_dir=/vagrant path=2016.pst type=pst
## cp: cannot stat â€/vagrant/2016.pstâ€™: No such file or directory

![file](https://cloud.githubusercontent.com/assets/16864128/17417511/042c39ce-5a94-11e6-9e45-6216e7ef2b3d.JPG)

**Comment by smahoney58** [comment]
Closing issue - ingest should be done through GUI which requires data be placed in a different location. Command line still works but location is /srv/software/pst-extraction-master/pst-extract/pst or /mbox or /eml depending on the data being ingested.
