### ISSUE TITLE
Conversation feature not working

### ISSUE THREAD

**Issue by smahoney58** [Sotera/newman#124]
The conversation feature is not returning all the email to/from two recipients.

**Comment by smahoney58** [comment]
o	Steps to reproduce
	Search for test
	Select the second email in the list “test email”
	Select checkbox for To: mmahoney@keywcorp.com
	Select Conversation button
o	Expected the list of email to filter down to the two emails between scott.mahoney@keywcorp.com and mmahoney@keywcorp.com.

**Comment by justinlueders** [comment]
fixed in Merlin stack v 0.07.17

**Comment by smahoney58** [comment]
Verified fixed in Merlin stack v 0.07.17
