### ISSUE TITLE
Duplicate entries in Topics

### ISSUE THREAD

**Issue by smahoney58** [Sotera/newman#130]
There are duplicate entries in Topics. Select the Topics tab and there are 4 entries for "email attachment purposes file etl" and then two more entries with the same words rearranged. 

May be due to the fact that its such a small dataset (9 emails).

**Comment by justinlueders** [comment]
@smahoney58  Please check this one against a larger dataset to verify that it is because of the small dataset.

**Comment by smahoney58** [comment]
Works fine against larger dataset. This issue can be closed.
