### ISSUE TITLE
ingest issue 

### ISSUE THREAD

**Issue by ghost** [Sotera/newman#56]
ingest err.log
Traceback (most recent call last):
  File "./ingest/mitie/mitie_entity_ingest_file.py", line 65, in <module>
    r = extract(email_id, body)
  File "./ingest/mitie/mitie_entity_ingest_file.py", line 29, in extract_entities
    for rng, tag in entities ]
ValueError: too many values to unpack 
#####
ingest tee.log
ingesting - email@dot.com 
working dir /srv/software/newman
ingest data
tx: 1
ingested count - 0 
entity extraction
loading NER model...

Tags output by this NER model: ['PERSON', 'LOCATION', 'ORGANIZATION', 'MISC']
class 'mysql.connector.errors.InternalError
#####
am i doing something wrong then ?

**Comment by cchabalk** [comment]
The ingest process has changed significantly.  Issue suggested closed by S. Mahoney.
